definitions:
  model.LicenseRequest:
    properties:
      is_active:
        type: boolean
      key:
        type: string
      username:
        type: string
    type: object
  model.LicenseResponse:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: integer
      is_active:
        type: boolean
      key:
        type: string
      updated_at:
        type: integer
      username:
        type: string
    type: object
  model.WebResponse:
    properties:
      code:
        type: integer
      data:
        type: any
      status:
        type: string
    type: object
info:
  contact:
    email: uloydev.gmail.com
    name: uloydev
  description: SISTEM TERDISTRIBUSI API BACKEND.
  title: SISTEM TERDISTRIBUSI API
  version: "1.0"
paths:
  /v1/license:
    get:
      consumes:
      - application/json
      description: get all License data from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.LicenseResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Get All License
      tags:
      - license
    post:
      consumes:
      - application/json
      description: Create New License
      parameters:
      - description: Create License
        in: body
        name: license
        required: true
        schema:
          $ref: '#/definitions/model.LicenseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.LicenseResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Create License
      tags:
      - license
  /v1/license/{id}:
    delete:
      consumes:
      - application/json
      description: Delete License
      parameters:
      - description: int valid
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Delete License
      tags:
      - license
    put:
      consumes:
      - application/json
      description: Update License
      parameters:
      - description: int valid
        in: path
        name: id
        type: integer
      - description: Update License
        in: body
        name: license
        required: true
        schema:
          $ref: '#/definitions/model.LicenseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.LicenseResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Update License
      tags:
      - License
  /v1/license/check:
    get:
      consumes:
      - application/json
      description: Check License
      parameters:
      - in: query
        name: key
        type: string
      - in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.LicenseResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.WebResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Check License
      tags:
      - License
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
